title: ManyMusic-stim
description: Documentation for ManyMusic-stim
version: 0.1.0
baseurl: "https://manymusic.net/stim/"
language: en
theme: just-the-docs

url: https://manymusic.net/stim/

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
