title: ManyMusic-Stim
description: Documentation for ManyMusic-Stim
version: 0.1.0
baseurl: manymusic.net
language: en
theme: just-the-docs
url: https://manymusic.net/stim/
aux_links:
  project-home: https://manymusic.net/
ga_trakcing: "G-3FHGYPZ4N9"
ga_tracking_anonymize_ip: true
# favicon_ico: /assets/img/favicon.ico